---
title: "Analysis - exp15"
output: html_notebook
---

# Libraries and helpers
```{r helper_fns, echo=FALSE, fig.width=6, fig.height=4, echo=FALSE, warning=FALSE, message=FALSE}
library(ggplot2)
library(grid)
library(gridExtra)
library(plyr)
library(readr)
library(dplyr)
library(png)
library(bspec)
library(psd)
library(tidyr)
library(patchwork)
library(scales)
library(ggpubr)
library(cowplot)
library(latex2exp)
# library(NNTbiomarker)
# library(bspec)

load.data1 <- function(path, type, stim_rates, qs, num_pops, pns){
  df <- NULL
  for(r_s in stim_rates){
    for(g in gs){
      for(n in num_pops){
        for(q in qs){
          try({
            name <- paste("stim_rate", as.character(r_s), 
                          "_g", as.character(g),
                          "_num_pop", as.character(n),
                          "_q", as.character(q),
                          "_", as.character(type), 
                          ".csv", sep="")
            di <- read.csv(paste(path, name, sep=""))
            di["stim_rate"] <- rep(r_s, nrow(di))
            di["g"] <- rep(g, nrow(di))
            di["num_pop"] <- rep(n, nrow(di))
            di["q"] <- rep(q, nrow(di))
            di["trial"] <- 1:nrow(di)
            df <- rbind(df, di)  
          })  
        }
      }
    }
  }
  df
}
```

# Load data
```{r}
path <- "~/Code/theoc/data/"

# -------------------------------------------------------
# num_pop - all
stim_rates <- c(10)
# gs <- c(1, 2, 3, 4, 5, 7, 8)
gs <- c(1, 4, 8)
num_pops <- c(40, 80, 160, 1280, 10240, 40960)
qs <- c("0.5")

exp_path <- paste(path, "/exp15/", sep="")
mi_exp15 <- load.data1(exp_path, "MI", stim_rates, qs, num_pops, qs)
dmi_exp15 <- load.data1(exp_path, "dMI", stim_rates, qs, num_pops, qs)
h_exp15 <- load.data1(exp_path, "H", stim_rates, qs, num_pops, qs)
pac_exp15 <- load.data1(exp_path, "PAC", stim_rates, qs, num_pops, qs)
pow_exp15 <- load.data1(exp_path, "power", stim_rates, qs, num_pops, qs)
```

# pop
```{r, fig.width=2.6, fig.height=4.2, echo=FALSE, warning=FALSE, message=FALSE}
dmi_exp15 %>% 
  gather(model, dmi, back_p:div_sub_p) %>% 
  filter(model %in% c("add_p", "mult_p", "sub_p", "div_sub_p")) -> 
  tmp1
pow_exp15 %>% 
  gather(model, pow, back_p:div_sub_p) %>% 
  filter(model %in% c("add_p", "mult_p", "sub_p", "div_sub_p")) -> 
  tmp2
tmp <- full_join(tmp1, tmp2)
tmp$model <- revalue(tmp$model, c("mult_p"="EI", "add_p"="E", "sub_p"="I", "div_sub_p"="II"))
tmp$model <- factor(tmp$model, levels=c("E", "EI", "I", "II"))

# --
tmp %>% 
  ggplot(aes(x=pow, y=dmi)) +
  geom_point(size=0.1, alpha=0.4) +
  geom_hline(yintercept=0, color="dark grey") + 
  # stat_smooth(method="lm", se = FALSE, alpha=1, color="darkgrey") +
  stat_smooth(aes(color=factor(g)), method="lm", se = FALSE, alpha=1, size=0.9) +
  scale_color_manual("g", values = c(
    "lightsteelblue3",
    "steelblue4",
    "mediumpurple4"
    )) +
  labs(y=expression(paste(Delta, "MI")), x="Peak power") +
  theme_classic() +
  theme(strip.background = element_blank()) +
  theme(legend.background = element_rect(colour ="black")) +
  theme(strip.text.x = element_text(angle = 0, face = "bold")) +
  theme(strip.text.y = element_text(angle = 0, face = "bold")) +
  theme(legend.key.size = unit(.3, "cm")) +
  theme(panel.spacing = unit(1, "lines")) +
  facet_grid(num_pop~model) 
```
