---
title: "Analysis - average, best, worst - many exps"
output: html_notebook
---

# Aim
I have looking at mean dMI. It is interesting to also look at the min/max. These are the best/worst costs and so could be very relevant?

# Libraries and helpers
```{r helper_fns, echo=FALSE, fig.width=6, fig.height=4, echo=FALSE, warning=FALSE, message=FALSE}
library(ggplot2)
library(grid)
library(gridExtra)
library(plyr)
library(readr)
library(dplyr)
library(png)
library(bspec)
library(psd)
library(tidyr)
library(patchwork)
library(scales)
library(ggpubr)
library(cowplot)
library(latex2exp)
# library(NNTbiomarker)
# library(bspec)

load.data1 <- function(path, type, stim_rates, qs, num_pops, pns){
  df <- NULL
  for(r_s in stim_rates){
    for(g in gs){
      for(n in num_pops){
        for(q in qs){
          try({
            name <- paste("stim_rate", as.character(r_s), 
                          "_g", as.character(g),
                          "_num_pop", as.character(n),
                          "_q", as.character(q),
                          "_", as.character(type), 
                          ".csv", sep="")
            di <- read.csv(paste(path, name, sep=""))
            di["stim_rate"] <- rep(r_s, nrow(di))
            di["g"] <- rep(g, nrow(di))
            di["num_pop"] <- rep(n, nrow(di))
            di["q"] <- rep(q, nrow(di))
            di["trial"] <- 1:nrow(di)
            df <- rbind(df, di)  
          })  
        }
      }
    }
  }
  df
}
```

# Load data
```{r}
path <- "~/Code/theoc/data/"

# -------------------------------------------------------
# num_pop - all
stim_rates <- c(10)
gs <- c(1, 2, 3, 4, 5, 7, 8)
# gs <- c(2, 4, 8)
num_pops <- c(10, 20, 40, 80, 160, 320, 640, 1280, 2560, 5120, 10240, 20480, 40960)
qs <- c("0.5")

exp_path <- paste(path, "/exp15/", sep="")
mi_exp15 <- load.data1(exp_path, "MI", stim_rates, qs, num_pops, qs)
dmi_exp15 <- load.data1(exp_path, "dMI", stim_rates, qs, num_pops, qs)
h_exp15 <- load.data1(exp_path, "H", stim_rates, qs, num_pops, qs)
pac_exp15 <- load.data1(exp_path, "PAC", stim_rates, qs, num_pops, qs)
pow_exp15 <- load.data1(exp_path, "power", stim_rates, qs, num_pops, qs)
```

# mean
```{r, fig.width=4.6, fig.height=1.4, echo=FALSE, warning=FALSE, message=FALSE}
# --------------------------------------------------------------
my_comparisons <- list(
  c("EI", "E"), c("EI", "I"), c("E", "I"),  c("EI", "II"), c("E", "II"), c("I", "II"))

# --------------------------------------------------------------
my_comparisons <- list(
  c("EI", "E"), c("EI", "I"), c("E", "I"),  c("EI", "II"), c("E", "II"), c("I", "II"))

dmi_exp15 %>%
  filter(stim_rate == 10) %>% 
  group_by(num_pop, g) %>%
  summarise(add_p=mean(add_p),
            back_p=mean(back_p),
            div_sub_p=mean(div_sub_p),
            mult_p=mean(mult_p),
            osc_p=mean(osc_p),
            stim_p=mean(stim_p),
            sub_p=mean(sub_p)) %>%
  ungroup() %>% 
  gather(model, mi, add_p:sub_p) %>% 
  filter(model %in% c("add_p","mult_p", "sub_p", "div_sub_p")) -> tmp

tmp$model <- revalue(tmp$model, c("mult_p"="EI", "add_p"="E", "sub_p"="I", "div_sub_p"="II")) 
tmp$model <- factor(tmp$model, levels=c("E", "EI", "I", "II"))

tmp %>% 
  ggplot(aes(x=model, y=mi)) +
  geom_jitter(size=.02, alpha=0.6, width=0.2) +
  stat_summary(aes(group=model), fun.y=mean, 
               geom="point", colour="black", alpha=1, size=10, shape="_") +
  geom_hline(yintercept=0, color="dark grey", size=0.5) + xlab("") +
  labs(y=expression(paste(Delta, "MI (bits)")), x="Model", title="Average case") +
  theme_classic() + 
  theme(plot.title = element_text(size = 10, face = "bold")) -> 
  p1

# ------------------------------------------------------------------------------
dmi_exp15 %>%
  filter(stim_rate == 10) %>% 
  group_by(num_pop, g) %>%
  summarise(add_p=mean(add_p),
            back_p=mean(back_p),
            div_sub_p=mean(div_sub_p),
            mult_p=mean(mult_p),
            osc_p=mean(osc_p),
            stim_p=mean(stim_p),
            sub_p=mean(sub_p)) %>% 
  gather(model, mi, add_p:sub_p) %>% 
  group_by(model, num_pop) %>%
  summarise(m=mean(mi), sd=sd(mi)) %>%
  filter(model %in% c("add_p","mult_p", "sub_p", "div_sub_p")) -> 
  tmp

# Set by hand. 
tmp$model <- revalue(tmp$model, c("mult_p"="EI", "add_p"="E", "sub_p"="I", "div_sub_p"="II")) 
tmp$model <- factor(tmp$model, levels=c("E", "EI", "I", "II"))

tmp %>% 
  ggplot(aes(x=num_pop,  y=m)) +
  geom_line(size=0.9, alpha=1) +
  # geom_ribbon(aes(ymean=m-sd, ymax=m+sd), alpha=0.2, color="grey") +
  geom_hline(yintercept=0, color="dark grey") + xlab("") +
  scale_x_log10() +
  annotation_logticks(sides="b") + 
  labs(y=expression(paste(Delta, "MI (bits)")), x="Population size") +
  theme_classic() +
  theme(strip.background = element_blank()) +
  theme(legend.background = element_rect(colour ="black")) +
  theme(legend.key.size = unit(.3, "cm")) +
  theme(panel.spacing = unit(1, "lines")) +
  theme(strip.text.x = element_text(face = "bold")) +
  facet_grid(.~model) ->
  p2

# --------------------------------------------------------------
## Build Figure
r1 <- p1 + p2 + plot_layout(widths = c(0.15, 0.85)) 
print(r1)
```

# min
```{r, fig.width=4.6, fig.height=1.4, echo=FALSE, warning=FALSE, message=FALSE}
# --------------------------------------------------------------
my_comparisons <- list(
  c("EI", "E"), c("EI", "I"), c("E", "I"),  c("EI", "II"), c("E", "II"), c("I", "II"))

dmi_exp15 %>%
  filter(stim_rate == 10) %>% 
  group_by(num_pop, g) %>%
  summarise(add_p=min(add_p),
            back_p=min(back_p),
            div_sub_p=min(div_sub_p),
            mult_p=min(mult_p),
            osc_p=min(osc_p),
            stim_p=min(stim_p),
            sub_p=min(sub_p)) %>%
  ungroup() %>% 
  gather(model, mi, add_p:sub_p) %>% 
  filter(model %in% c("add_p","mult_p", "sub_p", "div_sub_p")) -> tmp

tmp$model <- revalue(tmp$model, c("mult_p"="EI", "add_p"="E", "sub_p"="I", "div_sub_p"="II")) 
tmp$model <- factor(tmp$model, levels=c("E", "EI", "I", "II"))

tmp %>% 
  ggplot(aes(x=model, y=mi)) +
  geom_jitter(size=.02, alpha=0.6, width=0.2) +
  stat_summary(aes(group=model), fun.y=min, 
               geom="point", colour="black", alpha=1, size=10, shape="_") +
  geom_hline(yintercept=0, color="dark grey", size=0.5) + xlab("") +
  labs(y=expression(paste(Delta, "MI (bits)")), x="Model", title="Worst case") +
  theme_classic() + 
  theme(plot.title = element_text(size = 10, face = "bold")) -> 
  p3

# ------------------------------------------------------------------------------
dmi_exp15 %>%
  filter(stim_rate == 10) %>% 
  group_by(num_pop, g) %>%
  summarise(add_p=min(add_p),
            back_p=min(back_p),
            div_sub_p=min(div_sub_p),
            mult_p=min(mult_p),
            osc_p=min(osc_p),
            stim_p=min(stim_p),
            sub_p=min(sub_p)) %>% 
  gather(model, mi, add_p:sub_p) %>% 
  group_by(model, num_pop) %>%
  summarise(m=min(mi), sd=sd(mi)) %>%
  filter(model %in% c("add_p","mult_p", "sub_p", "div_sub_p")) -> 
  tmp

# Set by hand. 
tmp$model <- revalue(tmp$model, c("mult_p"="EI", "add_p"="E", "sub_p"="I", "div_sub_p"="II")) 
tmp$model <- factor(tmp$model, levels=c("E", "EI", "I", "II"))

tmp %>% 
  ggplot(aes(x=num_pop,  y=m)) +
  geom_line(size=0.9, alpha=1) +
  # geom_ribbon(aes(ymin=m-sd, ymax=m+sd), alpha=0.2, color="grey") +
  geom_hline(yintercept=0, color="dark grey") + xlab("") +
  scale_x_log10() +
  annotation_logticks(sides="b") + 
  labs(y=expression(paste(Delta, "MI (bits)")), x="Population size") +
  theme_classic() +
  theme(strip.background = element_blank()) +
  theme(legend.background = element_rect(colour ="black")) +
  theme(legend.key.size = unit(.3, "cm")) +
  theme(panel.spacing = unit(1, "lines")) +
  theme(strip.text.x = element_text(face = "bold")) +
  facet_grid(.~model) ->
  p4

# --------------------------------------------------------------
## Build Figure
r2 <- p3 + p4 + plot_layout(widths = c(0.15, 0.85)) 
print(r2)
```

# max
```{r, fig.width=4.6, fig.height=1.4, echo=FALSE, warning=FALSE, message=FALSE}
# --------------------------------------------------------------
my_comparisons <- list(
  c("EI", "E"), c("EI", "I"), c("E", "I"),  c("EI", "II"), c("E", "II"), c("I", "II"))

dmi_exp15 %>%
  filter(stim_rate == 10) %>% 
  group_by(num_pop, g) %>%
  summarise(add_p=max(add_p),
            back_p=max(back_p),
            div_sub_p=max(div_sub_p),
            mult_p=max(mult_p),
            osc_p=max(osc_p),
            stim_p=max(stim_p),
            sub_p=max(sub_p)) %>%
  ungroup() %>% 
  gather(model, mi, add_p:sub_p) %>% 
  filter(model %in% c("add_p","mult_p", "sub_p", "div_sub_p")) -> tmp

tmp$model <- revalue(tmp$model, c("mult_p"="EI", "add_p"="E", "sub_p"="I", "div_sub_p"="II")) 
tmp$model <- factor(tmp$model, levels=c("E", "EI", "I", "II"))

tmp %>% 
  ggplot(aes(x=model, y=mi)) +
  geom_jitter(size=.02, alpha=0.6, width=0.2) +
  stat_summary(aes(group=model), fun.y=max, 
               geom="point", colour="black", alpha=1, size=10, shape="_") +
  geom_hline(yintercept=0, color="dark grey", size=0.5) + xlab("") +
  labs(y=expression(paste(Delta, "MI (bits)")), x="Model", title="Best case") +
  theme_classic() + 
  theme(plot.title = element_text(size = 10, face = "bold")) -> 
  p5

# ------------------------------------------------------------------------------
dmi_exp15 %>%
  filter(stim_rate == 10) %>% 
  group_by(num_pop, g) %>%
  summarise(add_p=max(add_p),
            back_p=max(back_p),
            div_sub_p=max(div_sub_p),
            mult_p=max(mult_p),
            osc_p=max(osc_p),
            stim_p=max(stim_p),
            sub_p=max(sub_p)) %>% 
  gather(model, mi, add_p:sub_p) %>% 
  group_by(model, num_pop) %>%
  summarise(m=max(mi), sd=sd(mi)) %>%
  filter(model %in% c("add_p","mult_p", "sub_p", "div_sub_p")) -> 
  tmp

# Set by hand. 
tmp$model <- revalue(tmp$model, c("mult_p"="EI", "add_p"="E", "sub_p"="I", "div_sub_p"="II")) 
tmp$model <- factor(tmp$model, levels=c("E", "EI", "I", "II"))

tmp %>% 
  ggplot(aes(x=num_pop,  y=m)) +
  geom_line(size=0.9, alpha=1) +
  # geom_ribbon(aes(ymax=m-sd, ymax=m+sd), alpha=0.2, color="grey") +
  geom_hline(yintercept=0, color="dark grey") + xlab("") +
  scale_x_log10() +
  annotation_logticks(sides="b") + 
  labs(y=expression(paste(Delta, "MI (bits)")), x="Population size") +
  theme_classic() +
  theme(strip.background = element_blank()) +
  theme(legend.background = element_rect(colour ="black")) +
  theme(legend.key.size = unit(.3, "cm")) +
  theme(panel.spacing = unit(1, "lines")) +
  theme(strip.text.x = element_text(face = "bold")) +
  facet_grid(.~model) ->
  p6


# --------------------------------------------------------------
## Build Figure
r3 <- p5 + p6 + plot_layout(widths = c(0.15, 0.85)) 
print(r3)
```

# joint plot
```{r, fig.width=4.2, fig.height=3.8, echo=FALSE, warning=FALSE, message=FALSE}
## Build Figure
r1 / r2 / r3 +
  plot_annotation(tag_levels = 'a', tag_suffix = ".",
                  title="Population size: 40",
                  theme=theme(plot.title = element_text(size = 13, face = "bold")))
ggsave("figures/extrema1.pdf", dpi=300)
ggsave("figures/extrema1.png", dpi=300)
```