---
title: "Paper figures - Balanced oscillations improve information flow (2020 edition)"
output: html_notebook
---

# Libraries and helpers
```{r helper_fns, echo=FALSE, fig.width=6, fig.height=4, echo=FALSE, warning=FALSE, message=FALSE}
library(ggplot2)
library(grid)
library(gridExtra)
library(plyr)
library(readr)
library(dplyr)
library(png)
library(psd)
library(tidyr)
library(patchwork)
library(scales)
library(ggpubr)
library(cowplot)
library(latex2exp)
# library(NNTbiomarker)
# library(bspec)

load.data1 <- function(path, type, stim_rates, qs, num_pops, pns){
  df <- NULL
  for(r_s in stim_rates){
    for(g in gs){
      for(n in num_pops){
        for(q in qs){
          try({
            name <- paste("stim_rate", as.character(r_s), 
                          "_g", as.character(g),
                          "_num_pop", as.character(n),
                          "_q", as.character(q),
                          "_", as.character(type), 
                          ".csv", sep="")
            di <- read.csv(paste(path, name, sep=""))
            di["stim_rate"] <- rep(r_s, nrow(di))
            di["g"] <- rep(g, nrow(di))
            di["num_pop"] <- rep(n, nrow(di))
            di["q"] <- rep(q, nrow(di))
            di["trial"] <- 1:nrow(di)
            df <- rbind(df, di)  
          })  
        }
      }
    }
  }
  df
}
load.data2 <- function(path, type, fs){
  df <- NULL
  for(f in fs){
    try({
      # stim_rate-_2_g-11_num_pop-10_q-0.0_rate
      name <- paste("f", as.character(f), 
                    "_", as.character(type), 
                    ".csv", sep="")
      di <- read.csv(paste(path, name, sep=""))
      di["f"] <- rep(f, nrow(di))
      di["trial"] <- 1:nrow(di)
      df <- rbind(df, di)  
    })  
  }
  df
}
load.data3 <- function(path, type, osc_rates){
  df <- NULL
  for(o_r in osc_rates){
    try({
      # stim_rate-_2_g-11_num_pop-10_q-0.0_rate
      name <- paste("osc_rate", as.character(o_r), 
                    "_", as.character(type), 
                    ".csv", sep="")
      di <- read.csv(paste(path, name, sep=""))
      di["osc_rate"] <- rep(o_r, nrow(di))
      di["trial"] <- 1:nrow(di)
      df <- rbind(df, di)  
    })  
  }
  df
}
load.data4 <- function(path, type, ms){
  df <- NULL
  for(m in ms){
    try({
      # stim_rate-_2_g-11_num_pop-10_q-0.0_rate
      name <- paste("m", as.character(m), 
                    "_", as.character(type), 
                    ".csv", sep="")
      di <- read.csv(paste(path, name, sep=""))
      di["m"] <- rep(m, nrow(di))
      di["trial"] <- 1:nrow(di)
      df <- rbind(df, di)  
    })  
  }
  df
}
load.data5 <- function(path, type, num_backgrounds){
  df <- NULL
  for(n_b in num_backgrounds){
    try({
      # stim_rate-_2_g-11_num_pop-10_q-0.0_rate
      name <- paste("num_background", as.character(n_b), 
                    "_", as.character(type), 
                    ".csv", sep="")
      di <- read.csv(paste(path, name, sep=""))
      di["num_background"] <- rep(n_b, nrow(di))
      di["trial"] <- 1:nrow(di)
      df <- rbind(df, di)  
    })  
  }
  df
}
load.data6 <- function(path, type, num_pops){
  df <- NULL
  for(n_p in num_pops){
    try({
      # stim_rate-_2_g-11_num_pop-10_q-0.0_rate
      name <- paste("num_pop", as.character(n_p), 
                    "_", as.character(type), 
                    ".csv", sep="")
      di <- read.csv(paste(path, name, sep=""))
      di["num_pop"] <- rep(n_p, nrow(di))
      di["trial"] <- 1:nrow(di)
      df <- rbind(df, di)  
    })  
  }
  df
}
```

# Load data
## Exp - the main results 
```{r load1, message=FALSE, warning=FALSE, error=FALSE}
path <- "~/Code/theoc/data/"

stim_rates <- c(5, 10, 15, 20, 25, 30)
gs <- c(1, 2, 3, 4, 5, 6, 7, 8)
num_pops <- c(50)
qs <- c("0.05", "0.25", "0.5", "0.75", "1.0")

exp1path <- paste(path, "/exp8/", sep="")
mi_exp8 <- load.data1(exp1path, "MI", stim_rates, qs, num_pops, qs)
dmi_exp8 <- load.data1(exp1path, "dMI", stim_rates, qs, num_pops, qs)
h_exp8 <- load.data1(exp1path, "H", stim_rates, qs, num_pops, qs)
pac_exp8 <- load.data1(exp1path, "PAC", stim_rates, qs, num_pops, qs)
pow_exp8 <- load.data1(exp1path, "power", stim_rates, qs, num_pops, qs)
```

## Exp - control experiments
```{r load26, message=FALSE, warning=FALSE, error=FALSE}
path <- "~/Code/theoc/data/"

# exp9
fs <- c(4, 6, 8, 12, 20, 30)
exp_path <- paste(path, "/exp9/", sep="")
mi_exp9 <- load.data2(exp_path, "MI", fs)
dmi_exp9 <- load.data2(exp_path, "dMI", fs)
h_exp9 <- load.data2(exp_path, "H", fs)

# exp10
osc_rates <- c(2, 3, 4, 6, 8)
exp_path <- paste(path, "/exp10/", sep="")
mi_exp10 <- load.data3(exp_path, "MI", osc_rates)
dmi_exp10 <- load.data3(exp_path, "dMI", osc_rates)
h_exp10 <- load.data3(exp_path, "H", osc_rates)

# exp11
ms <- c(5, 10, 20)
exp_path <- paste(path, "/exp11/", sep="")
mi_exp11 <- load.data4(exp_path, "MI", ms)
dmi_exp11 <- load.data4(exp_path, "dMI", ms)
h_exp11 <- load.data4(exp_path, "H", ms)

# exp12
num_backgrounds <- c(5, 10, 15, 20, 25)
exp_path <- paste(path, "/exp12/", sep="")
mi_exp12 <- load.data5(exp_path, "MI", num_backgrounds)
dmi_exp12 <- load.data5(exp_path, "dMI", num_backgrounds)
h_exp12 <- load.data5(exp_path, "H", num_backgrounds)

# exp6
num_pops <- c(10, 20, 40, 80, 160, 320, 640, 1280)
exp_path <- paste(path, "/exp6/", sep="")
mi_exp6 <- load.data6(exp_path, "MI", num_pops)
dmi_exp6 <- load.data6(exp_path, "dMI", num_pops)
h_exp6 <- load.data6(exp_path, "H", num_pops)
```

## Exp - II results
```{r, message=FALSE, warning=FALSE, error=FALSE}
stim_rates <- c(5, 10, 15, 20, 25, 30)
gs <- c(1, 2, 3, 4, 5, 6, 7, 8)
num_pops <- c(50)
qs <- c("0.05", "0.25", "0.5", "0.75", "0.95")

exp_path <- paste(path, "/exp13/", sep="")
mi_exp13 <- load.data1(exp_path, "MI", stim_rates, qs, num_pops, qs)
dmi_exp13 <- load.data1(exp_path, "dMI", stim_rates, qs, num_pops, qs)
h_exp13 <- load.data1(exp_path, "H", stim_rates, qs, num_pops, qs)
pac_exp13 <- load.data1(exp_path, "PAC", stim_rates, qs, num_pops, qs)
pow_exp13 <- load.data1(exp_path, "power", stim_rates, qs, num_pops, qs)
```

# Figure - FI
```{r, fig.width=0.8, fig.height=1.4, echo=FALSE, warning=FALSE, message=FALSE}
phi1 <- function(x) {
  30 / (1 + exp(-.2*x + 5))
}

phi2 <- function(x, m, b) {
  x <- x - b
  x[x <= 0] <- 0
  x <- x * m
}

input = -20:40
fi = data.frame(
  input=input,
  ref=phi2(input, 1, 0), 
  E=phi2(input+10, 1, 0), 
  I=phi2(input-10, 1, 0), 
  EI=phi2(input*1.5, 1, 0))

fi %>% 
  gather(model, fi, E:EI) -> fi

fi$model <- factor(fi$model, levels=c("EI", "E", "I"))

fi %>% 
  filter(model != "ref") %>% 
  ggplot(aes(x=input, y=fi)) +
  geom_line() +
  geom_line(aes(x=input, y=ref), color="black", linetype = 2) +
  facet_grid(model~.) +
  labs(x="Input", y="Output", title="Neural arithmetic") +
  theme_classic2() +
  theme(plot.title = element_text(size = 7, hjust=1, face = "bold")) +
  theme(strip.background = element_blank()) +
  theme(legend.background = element_rect(colour ="black")) +
  theme(legend.key.size = unit(.3, "cm")) +
  theme(strip.text.y = element_text(face = "bold", angle = 0)) ->
  p1

p1
ggsave("figures/arithmetic.pdf", dpi=600)
```

# Figure - Timecourse
```{r, fig.width=2.5, fig.height=4, echo=FALSE, warning=FALSE, message=FALSE}
examples <- read_csv("../data/examples.csv")

# S
examples %>% 
  ggplot(aes(x=times, y=stim_ref)) +
  geom_line(color="darkgrey", size=1.1) +
  scale_y_continuous(breaks=c(0, 0.5, 1), limits=c(0, 1)) +
  theme_classic2() + 
  labs(x="", y="S", title="Timecourse examples") + 
  theme(axis.title.y=element_text(angle = 0, vjust = 0.5, face = "bold")) +
  theme(plot.title = element_text(size = 9, hjust=1, face = "bold")) ->
p4

# O
examples %>% 
  ggplot(aes(x=times, y=osc_ref)) +
  geom_line(size=1.2) +
  scale_y_continuous(breaks=c(0, 0.5, 1), limits=c(0, 1)) +
  theme_classic2() + 
  labs(x="", y="O") +
  theme(axis.title.y=element_text(angle = 0, vjust = 0.5, face = "bold")) -> 
p5

# EI
examples %>% 
  ggplot(aes(x=times, y=mult_p)) +
  geom_line() +
  geom_line(aes(x=times, y=stim_ref), color="darkgrey", size=1.1) +
  scale_y_continuous(breaks=c(0, 0.5, 1), limits=c(0, 1)) +
  theme_classic2() + 
  labs(x="", y="EI") +
  theme(axis.title.y=element_text(angle = 0, vjust = 0.5, face = "bold")) -> 
p6

# E
examples %>% 
  ggplot(aes(x=times, y=add_p)) +
  geom_line() +
  geom_line(aes(x=times, y=stim_ref), color="darkgrey", size=1.1) +
  scale_y_continuous(breaks=c(0, 0.5, 1), limits=c(0, 1)) +
  theme_classic2() + 
  labs(x="", y="E") +
  theme(axis.title.y=element_text(angle = 0, vjust = 0.5, face = "bold")) -> 
p7

# I
examples %>% 
  ggplot(aes(x=times, y=sub_p)) +
  geom_line() +
  geom_line(aes(x=times, y=stim_ref), color="darkgrey", size=1.2) +
  scale_y_continuous(breaks=c(0, 0.5, 1), limits=c(0, 1)) +
  theme_classic2() + 
  labs(x="Time", y="I") +
  theme(axis.title.y=element_text(angle = 0, vjust = 0.5, face = "bold")) -> 
p8

p4 / p5 / p6 / p7 / p8 + 
  plot_annotation(tag_levels = 'a', tag_suffix = ".")
ggsave("figures/example.pdf", dpi=600)
```
# Figure - Entropy and probability
```{r, fig.width=1, fig.height=2, echo=FALSE, warning=FALSE, message=FALSE}
examples <- read_csv("../data/examples.csv")
example_dists <- read_csv("../data/example_dists.csv")

examples %>% 
  ggplot(aes(x=times, y=stim_ref)) +
  geom_line(color="darkgrey", size=1.1) +
  scale_y_continuous(breaks=c(0, 0.5, 1), limits=c(0, 1)) +
  geom_hline(yintercept=1, color="grey", size=0.2) +
  geom_hline(yintercept=0.9, color="grey", size=0.2) +
  geom_hline(yintercept=0.8, color="grey", size=0.2) +
  geom_hline(yintercept=0.7, color="grey", size=0.2) +
  geom_hline(yintercept=0.6, color="grey", size=0.2) +
  geom_hline(yintercept=0.5, color="grey", size=0.2) +
  geom_hline(yintercept=0.4, color="grey", size=0.2) +
  geom_hline(yintercept=0.3, color="grey", size=0.2) +
  geom_hline(yintercept=0.2, color="grey", size=0.2) +
  geom_hline(yintercept=0.1, color="grey", size=0.2) +
  labs(x="Time", y="S", title="Discretize into m bins") +
  theme_classic2() + 
  theme(axis.title.y=element_text(angle = 0, vjust = 0.5)) +
  theme(plot.title = element_text(size = 7, hjust=1, face = "bold")) ->
p1

del <- -0.5
example_dists %>% 
  ggplot(aes(x=m, y=stim_ref)) +
  geom_bar(fill="darkgrey", alpha=0.6, stat="identity") +
  scale_x_continuous(breaks=0:9, labels=1:10) +
  geom_vline(xintercept=0+del, color="grey", size=0.2) +
  geom_vline(xintercept=1+del, color="grey", size=0.2) +
  geom_vline(xintercept=2+del, color="grey", size=0.2) +
  geom_vline(xintercept=3+del, color="grey", size=0.2) +
  geom_vline(xintercept=4+del, color="grey", size=0.2) +
  geom_vline(xintercept=5+del, color="grey", size=0.2) +
  geom_vline(xintercept=6+del, color="grey", size=0.2) +
  geom_vline(xintercept=7+del, color="grey", size=0.2) +
  geom_vline(xintercept=8+del, color="grey", size=0.2) +
  geom_vline(xintercept=9+del, color="grey", size=0.2) +
  geom_vline(xintercept=10+del, color="grey", size=0.2) +
  labs(y="Probability", x="m", title="Estimate m probabilities") +
  lims(y=c(0,1)) +
  theme_classic2() +
  theme(plot.title = element_text(size = 7, hjust=1, face = "bold")) -> p2

p_h <- as_ggplot(
  text_grob(TeX("\\sum_m \\frac{p log p}{log m} = \\frac{H_m}{H_{max}}"), vjust = 0.7, hjust=0.75)) +
  labs(title="Estimate entropy") +
  theme(plot.title = element_text(size = 7, hjust=0, vjust = 0, face = "bold"))

# ----------------------------------------------------
## Build
b1 <- ((p1 / p2) + plot_annotation(tag_levels = 'a', tag_suffix = "."))
b2 <- p_h
b1 /  b2  
ggsave("figures/entropy.pdf", dpi=600)
```
# Figure - Dists
```{r, fig.width=1.1, fig.height=2.25, echo=FALSE, warning=FALSE, message=FALSE}
example_dists <- read_csv("../data/example_dists.csv")

example_dists %>% 
  ggplot(aes(x=m, y=stim_ref)) +
  geom_bar(stat="identity", fill="darkgrey", alpha=0.6, alpha=1) +
  scale_x_continuous(breaks=0:9, labels=1:10) +
  labs(y="", x="", title="Example distributions") +
  lims(y=c(0,1)) +
  theme_classic2() + 
  theme(plot.title = element_text(size = 7, hjust=1, face = "bold")) +
  theme(axis.text.x=element_blank()) -> p0

example_dists %>% 
  ggplot(aes(x=m, y=mult_p)) +
  geom_bar(stat="identity", alpha=1) +
  geom_bar(aes(x=m, y=stim_ref), fill="darkgrey", alpha=0.6, stat="identity") +
  scale_x_continuous(breaks=0:9, labels=1:10) +
  labs(y="", x="") +
  lims(y=c(0,1)) +
  theme_classic2() + 
  theme(plot.title = element_text(size = 7, hjust=1, face = "bold")) +
  theme(axis.text.x=element_blank()) -> p1

example_dists %>% 
  ggplot(aes(x=m, y=add_p)) +
  geom_bar(stat="identity", alpha=1) +
  geom_bar(aes(x=m, y=stim_ref), fill="darkgrey", alpha=0.6, stat="identity") +
  scale_x_continuous(breaks=0:9, labels=1:10) +
  labs(y="", x="") +
  lims(y=c(0,1)) +
  theme_classic2() + 
  theme(axis.text.x=element_blank()) -> p2

example_dists %>% 
  ggplot(aes(x=m, y=sub_p)) +
  geom_bar(stat="identity", alpha=1) +
  geom_bar(aes(x=m, y=stim_ref), fill="darkgrey", alpha=0.6, stat="identity") +
  scale_x_continuous(breaks=0:9, labels=1:10) +
  labs(y="", x="m") +
  lims(y=c(0,1)) +
  theme_classic2() -> p3

y_label <- as_ggplot(text_grob("Probability", hjust=0, rot = 90))
p0_label <- as_ggplot(text_grob("S", hjust=1, face="bold"))
p1_label <- as_ggplot(text_grob("EI", hjust=1, face="bold"))
p2_label <- as_ggplot(text_grob("E", hjust=1, face="bold"))
p3_label <- as_ggplot(text_grob("I", hjust=1, face="bold"))

b0 <- p0 + p0_label + plot_layout(widths = c(0.8, 0.2))
b1 <- p1 + p1_label + plot_layout(widths = c(0.8, 0.2))
b2 <- p2 + p2_label + plot_layout(widths = c(0.8, 0.2))
b3 <- p3 + p3_label + plot_layout(widths = c(0.8, 0.2))

b <- (b0 / b1 / b2 / b3) 
y_label + b + plot_layout(widths = c(0.1, 0.9))
ggsave("figures/dist.pdf", dpi=600)
```

# Figure - Overall - Mutual information and oscillation
```{r, fig.width=3.5, fig.height=1.1, echo=FALSE, warning=FALSE, message=FALSE}
dmi_exp8 %>% 
  filter(q == "0.05") %>% 
  filter(num_pop == 50) %>% 
  gather(model, mi, back_p:div_sub_p) %>% 
  filter(model %in% c("add_p", "mult_p", "sub_p")) -> 
  tmp

tmp$model <- revalue(tmp$model, c("mult_p"="EI", "add_p"="E", "sub_p"="I")) 
tmp$model <- factor(tmp$model, levels=c("EI", "E", "I"))

my_comparisons <- list( c("EI", "E"), c("EI", "I"), c("E", "I") )

# --------------------------------------------------------------
# Models overall
tmp %>% 
  ggplot(aes(x=model, y=mi)) +
  lims(y=c(-.3, 0.5)) +
  geom_jitter(size=.04, alpha=0.15) +
  stat_summary(aes(group=model), fun.y=median, 
               geom="point", colour="grey", alpha=1, size=10, shape="_") +
  geom_hline(yintercept=0, color="dark grey") + xlab("") +
  labs(y=expression(paste(Delta, "MI")), x="") +
  stat_compare_means(comparisons = my_comparisons, label = "p.signif", label.y = c(0.45, 0.32, 0.15)) +
  theme_classic() ->
  p1

# --------------------------------------------------------------
# Osc overall
dmi_exp8 %>% 
  filter(q == "0.05") %>% 
  filter(num_pop == 50) %>% 
  gather(model, mi, back_p:div_sub_p) %>% 
  filter(model %in% c("osc_p")) -> tmp

tmp$model <- revalue(tmp$model, c("osc_p"="O")) 

tmp %>% 
  ggplot(aes(x=model, y=mi)) +
  geom_jitter(size=.04, alpha=0.15) +
  stat_summary(aes(group=model), fun.y=median, 
               geom="point", colour="grey", alpha=1, size=10, shape="_") +
  geom_hline(yintercept=0, color="dark grey") + xlab("") +
  lims(y=c(-.35, 0.5)) +
  labs(y=expression(paste(Delta, "MI")), x="") +
  theme_classic() -> 
  p2
# plot(p2)

# --------------------------------------------------------------
## Timecourses
dmi_exp8 %>% 
  filter(q == "0.05") %>% 
  filter(num_pop == 50) %>% 
  group_by(stim_rate, g, num_pop) %>%
  summarise(add_p=mean(add_p),
            back_p=mean(back_p),
            div_sub_p=mean(div_sub_p),
            mult_p=mean(mult_p),
            osc_p=mean(osc_p),
            stim_p=mean(stim_p),
            sub_p=mean(sub_p)) %>%
  ungroup() %>%
  gather(model, mi, add_p:sub_p) %>% 
  filter(model %in% c("add_p","mult_p", "sub_p")) -> 
  tmp

tmp$model <- revalue(tmp$model, c("mult_p"="EI", "add_p"="E", "sub_p"="I")) 
tmp$model <- factor(tmp$model, levels=c("EI", "E", "I"))

tmp %>% 
  ggplot(aes(x=stim_rate, y=mi, color=factor(g), group=factor(g))) +
  geom_line(size=0.5, alpha=0.9) +
  geom_point(size=0.7, alpha=1) +
  geom_hline(yintercept=0, color="dark grey") + xlab("") +
  lims(y=c(-.3, 0.5)) +
  labs(y=expression(paste(Delta, "MI")), x="Stimulus firing rate") +
  scale_color_manual("g", values = c(
    "lightsteelblue3",
    "lightskyblue3",
    "steelblue3",
    "steelblue4",
    "slateblue2", 
    "slateblue3",
    "mediumpurple4"
    )) +
  theme_classic() +
  theme(strip.background = element_blank()) +
  theme(legend.background = element_rect(colour ="black")) +
  theme(legend.key.size = unit(.3, "cm")) +
  theme(strip.text.x = element_text(face = "bold")) +
  facet_grid(.~model) ->
  p3
# plot(p3)

# --------------------------------------------------------------
## Build Figure 
p1 + p2 + p3 + 
  plot_layout(widths = c(0.2, 0.08, 0.7)) +
  plot_annotation(tag_levels = 'a', tag_suffix = ".")
ggsave("figures/mi.pdf", dpi=600)
```
### Sig test results 
- For the paper.
```{r}
compare_means(mi~model, tmp)
```


# Figure - Control exps for MI
```{r, fig.width=2.1, fig.height=4.4, echo=FALSE, warning=FALSE, message=FALSE}
dmi_exp9 %>% 
  gather(model, mi, back_p:div_sub_p) %>% 
  filter(model %in% c("add_p","mult_p", "sub_p")) -> 
  tmp

tmp$model <- revalue(tmp$model, c("mult_p"="EI", "add_p"="E", "sub_p"="I")) 
tmp$model <- factor(tmp$model, levels=c("EI", "E", "I"))

# --------------------------------------------------------------
## Panel - Osc. freq.
tmp %>% 
  ggplot(aes(x=f, y=mi)) +
  geom_point(size=.3, alpha=0.2) +
  geom_hline(yintercept=0, color="darkgrey") + xlab("") +
  lims(x=c(1, 30), y=c(-0.3, 0.5)) + 
  labs(y=expression(paste(Delta, "MI")), x="Oscillation frequency") +
  theme_classic() +
  theme(strip.background = element_blank()) +
  theme(strip.text.x = element_text(face = "bold")) +
  facet_wrap(model~., nrow=1) ->
  p1

# --------------------------------------------------------------
## Panel - Osc. firing rate
dmi_exp10 %>% 
  gather(model, mi, back_p:div_sub_p) %>% 
  filter(model %in% c("add_p","mult_p", "sub_p"))-> 
  tmp

tmp$model <- revalue(tmp$model, c("mult_p"="EI", "add_p"="E", "sub_p"="I")) 
tmp$model <- factor(tmp$model, levels=c("EI", "E", "I"))

tmp %>% 
  ggplot(aes(x=osc_rate, y=mi)) +
  geom_point(size=.3, alpha=0.2) +
  geom_hline(yintercept=0, color="grey") + xlab("") +
  labs(y=expression(paste(Delta, "MI")), x="Oscillation firing rate") +
  lims(x=c(1, 8), y=c(-0.3, 0.5)) +
  theme_classic() +
  theme(strip.text.x = element_text(face = "bold")) +
  theme(strip.background = element_blank()) +
  facet_wrap(model~., nrow=1) ->
  p2

# --------------------------------------------------------------
## Panel - Population size
dmi_exp6 %>% 
  gather(model, mi, back_p:div_sub_p) %>% 
  filter(model %in% c("add_p","mult_p", "sub_p"))-> 
  tmp

tmp$model <- revalue(tmp$model, c("mult_p"="EI", "add_p"="E", "sub_p"="I")) 
tmp$model <- factor(tmp$model, levels=c("EI", "E", "I"))

tmp %>% 
  ggplot(aes(x=num_pop, y=mi)) +
  geom_point(size=.3, alpha=0.2) +
  geom_hline(yintercept=0, color="grey") +
  lims(y=c(-0.3, 0.5)) +
  scale_x_log10()+
  annotation_logticks(base = 10, sides = "b") +
  labs(y=expression(paste(Delta, "MI")), x="Population size") +
  theme_classic() +
  theme(strip.text.x = element_text(face = "bold")) +
  theme(strip.background = element_blank()) +
  facet_wrap(model~., nrow=1) ->
  p3

# --------------------------------------------------------------
## Panel - Background
dmi_exp12 %>% 
  gather(model, mi, back_p:div_sub_p) %>% 
  filter(model %in% c("add_p","mult_p", "sub_p"))-> 
  tmp

tmp$model <- revalue(tmp$model, c("mult_p"="EI", "add_p"="E", "sub_p"="I")) 
tmp$model <- factor(tmp$model, levels=c("EI", "E", "I"))

tmp %>% 
  ggplot(aes(x=num_background, y=mi)) +
  geom_point(size=.3, alpha=0.2) +
  geom_hline(yintercept=0, color="grey") + xlab("") +
  lims(y=c(-0.3, 0.5)) +
  labs(y=expression(paste(Delta, "MI")), x="Background size") +
  theme_classic() +
  theme(strip.background = element_blank()) +
  theme(strip.text.x = element_text(face = "bold")) +
  facet_wrap(model~., nrow=1) ->
  p4

# --------------------------------------------------------------
## Panel - Bin size
dmi_exp11 %>% 
  gather(model, mi, back_p:div_sub_p) %>% 
  filter(model %in% c("add_p","mult_p", "sub_p"))-> 
  tmp

tmp$model <- revalue(tmp$model, c("mult_p"="EI", "add_p"="E", "sub_p"="I")) 
tmp$model <- factor(tmp$model, levels=c("EI", "E", "I"))

tmp$m <- as.character((tmp$m))
tmp$m <- revalue(tmp$m, c("5"="m/2", "10"="m", "20"="2m")) 
tmp$m <- factor(tmp$m, levels=c("m/2", "m", "2m"))
tmp %>% 
  ggplot(aes(x=m, y=mi)) +
  geom_point(size=.3, alpha=0.2) +
  geom_hline(yintercept=0, color="grey") + xlab("") +
  lims(y=c(-0.3, 0.5)) +
  labs(y=expression(paste(Delta, "MI")), x="Entropy bin size (m)") +
  theme_classic() +
  theme(strip.background = element_blank()) +
  theme(strip.text.x = element_text(face = "bold")) +
  facet_wrap(model~., nrow=1) -> 
  p5

# --------------------------------------------------------------
p1 / p2 / p3 / p4 / p5 + 
  plot_annotation(tag_levels = 'a', tag_suffix = ".")
ggsave("figures/control.pdf", dpi=600)
```
# Figure - Power (spectral) and info
```{r, fig.width=1.6, fig.height=3.1, echo=FALSE, warning=FALSE, message=FALSE}
# E, I, IE
h_exp8 %>% 
  filter(q == "0.05") %>% 
  filter(num_pop == 50) %>% 
  gather(model, h, back_p:div_sub_p) %>% 
  filter(model %in% c("add_p", "mult_p", "sub_p")) -> 
  tmp1

mi_exp8 %>% 
  filter(q == "0.05") %>% 
  filter(num_pop == 50) %>% 
  gather(model, mi, back_p:div_sub_p) %>% 
  filter(model %in% c("add_p", "mult_p", "sub_p")) -> 
  tmp2

dmi_exp8 %>% 
  filter(q == "0.05") %>% 
  filter(num_pop == 50) %>% 
  gather(model, dmi, back_p:div_sub_p) %>% 
  filter(model %in% c("add_p", "mult_p", "sub_p")) -> 
  tmp3

pow_exp8 %>% 
  filter(q == "0.05") %>% 
  filter(num_pop == 50) %>% 
  gather(model, pow, back_p:div_sub_p) %>% 
  filter(model %in% c("add_p", "mult_p", "sub_p")) -> 
  tmp4

tmp <- full_join(tmp1, tmp2)
tmp <- full_join(tmp, tmp3)
tmp <- full_join(tmp, tmp4)

tmp$model <- revalue(tmp$model, c("mult_p"="EI", "add_p"="E", "sub_p"="I"))
tmp$model <- factor(tmp$model, levels=c("EI", "E", "I"))

tmp %>% 
  filter(stim_rate == 20, model == "EI") %>% 
  ggplot(aes(x=pow, y=dmi, color=factor(g))) +
  geom_point(size=1.2, alpha=0.2) +
  scale_color_manual("g", values = c(
    "lightsteelblue3",
    "lightskyblue3",
    "steelblue3",
    "steelblue4",
    "slateblue2", 
    "slateblue3",
    "mediumpurple4"
    )) +
  stat_smooth(method="lm", se = FALSE, alpha=1) +
  geom_hline(yintercept=0, color="dark grey") + 
  labs(y=expression(paste(Delta, "MI")), x="Spectral power", title="Power and MI") +
  theme_classic2() +
  theme(plot.title = element_text(size = 9, hjust=1, face = "bold")) +
  theme(strip.background = element_blank()) +
  theme(legend.background = element_rect(colour ="black")) +
  theme(legend.key.size = unit(.3, "cm")) +
  theme(legend.position = "none") +
  theme(strip.text.x = element_blank()) +
  theme(strip.text.y = element_text(angle = 0, face = "bold")) +
  facet_grid(model~., scale = "free_y") ->
  p1

tmp %>% 
  filter(stim_rate == 20, model == "E") %>% 
  ggplot(aes(x=pow, y=dmi, color=factor(g))) +
  geom_point(size=1.2, alpha=0.2) +
  scale_color_manual("g", values = c(
    "lightsteelblue3",
    "lightskyblue3",
    "steelblue3",
    "steelblue4",
    "slateblue2", 
    "slateblue3",
    "mediumpurple4"
    )) +
  stat_smooth(method="lm", se = FALSE, alpha=1) +
  geom_hline(yintercept=0, color="dark grey") + 
  labs(y=expression(paste(Delta, "MI")), x="Spectral power") +
  theme_classic2() +
  theme(strip.background = element_blank()) +
  theme(legend.background = element_rect(colour ="black")) +
  theme(legend.key.size = unit(.3, "cm")) +
  theme(strip.text.x = element_blank()) +
  theme(strip.text.y = element_text(angle = 0, face = "bold")) +
  facet_grid(model~., scale = "free_y") ->
  p2

tmp %>% 
  filter(stim_rate == 20, model == "I") %>% 
  ggplot(aes(x=pow, y=dmi, color=factor(g))) +
  geom_point(size=1.2, alpha=0.2) +
  scale_color_manual("g", values = c(
    "lightsteelblue3",
    "lightskyblue3",
    "steelblue3",
    "steelblue4",
    "slateblue2", 
    "slateblue3",
    "mediumpurple4"
    )) +
  stat_smooth(method="lm", se = FALSE, alpha=1) +
  geom_hline(yintercept=0, color="dark grey") + 
  labs(y=expression(paste(Delta, "MI")), x="Spectral power") +
  theme_classic2() +
  theme(strip.background = element_blank()) +
  theme(legend.position = "none") +
  theme(legend.background = element_rect(colour ="black")) +
  theme(legend.key.size = unit(.3, "cm")) +
  theme(strip.text.x = element_blank()) +
  theme(strip.text.y = element_text(angle = 0, face = "bold")) +
  facet_grid(model~., scale = "free_y") ->
  p3

p1 / p2 / p3 + plot_layout(guides = "collect") +
  plot_annotation(tag_levels = 'a', tag_suffix = ".")
ggsave("figures/pow.pdf", dpi=600)
```

# Figure - PAC and info
```{r, fig.width=1.6, fig.height=3.1, echo=FALSE, warning=FALSE, message=FALSE}
# E, I, IE
h_exp8 %>% 
  filter(q == "0.05") %>% 
  filter(num_pop == 50) %>% 
  gather(model, h, back_p:div_sub_p) %>% 
  filter(model %in% c("add_p", "mult_p", "sub_p")) -> 
  tmp1

mi_exp8 %>% 
  filter(q == "0.05") %>% 
  filter(num_pop == 50) %>% 
  gather(model, mi, back_p:div_sub_p) %>% 
  filter(model %in% c("add_p", "mult_p", "sub_p")) -> 
  tmp2

dmi_exp8 %>% 
  filter(q == "0.05") %>% 
  filter(num_pop == 50) %>% 
  gather(model, dmi, back_p:div_sub_p) %>% 
  filter(model %in% c("add_p", "mult_p", "sub_p")) -> 
  tmp3

pac_exp8 %>% 
  filter(q == "0.05") %>% 
  filter(num_pop == 50) %>% 
  gather(model, pac, back_p:div_sub_p) %>% 
  filter(model %in% c("add_p", "mult_p", "sub_p")) -> 
  tmp4

tmp <- full_join(tmp1, tmp2)
tmp <- full_join(tmp, tmp3)
tmp <- full_join(tmp, tmp4)

tmp$model <- revalue(tmp$model, c("mult_p"="EI", "add_p"="E", "sub_p"="I"))
tmp$model <- factor(tmp$model, levels=c("EI", "E", "I"))

tmp %>% 
  filter(stim_rate == 20, model == "EI") %>% 
  ggplot(aes(x=pac, y=dmi, color=factor(g))) +
  geom_point(size=1.2, alpha=0.2) +
  scale_color_manual("g", values = c(
    "lightsteelblue3",
    "lightskyblue3",
    "steelblue3",
    "steelblue4",
    "slateblue2", 
    "slateblue3",
    "mediumpurple4"
    )) +
  stat_smooth(method="lm", se = FALSE, alpha=1) +
  geom_hline(yintercept=0, color="dark grey") + 
  labs(y=expression(paste(Delta, "MI")), x="Phase-amplitude coupling", title="PAC and MI") +
  theme_classic2() +
  theme(strip.background = element_blank()) +
  theme(legend.background = element_rect(colour ="black")) +
  theme(legend.key.size = unit(.3, "cm")) +
  theme(legend.position = "none") +
  theme(strip.text.x = element_blank()) +
  theme(plot.title = element_text(size = 9, hjust=1, face = "bold")) +
  theme(strip.text.y = element_text(angle = 0, face = "bold")) +
  facet_grid(model~., scale = "free_y") ->
  p1

tmp %>% 
  filter(stim_rate == 20, model == "E") %>% 
  ggplot(aes(x=pac, y=dmi, color=factor(g))) +
  geom_point(size=1.2, alpha=0.2) +
  scale_color_manual("g", values = c(
    "lightsteelblue3",
    "lightskyblue3",
    "steelblue3",
    "steelblue4",
    "slateblue2", 
    "slateblue3",
    "mediumpurple4"
    )) +
  stat_smooth(method="lm", se = FALSE, alpha=1) +
  geom_hline(yintercept=0, color="dark grey") + 
  labs(y=expression(paste(Delta, "MI")), x="Phase-amplitude coupling") +
  theme_classic2() +
  theme(strip.background = element_blank()) +
  theme(legend.background = element_rect(colour ="black")) +
  theme(legend.key.size = unit(.3, "cm")) +
  theme(strip.text.x = element_blank()) +
  theme(strip.text.y = element_text(angle = 0, face = "bold")) +
  facet_grid(model~., scale = "free_y") ->
  p2

tmp %>% 
  filter(stim_rate == 20, model == "I") %>% 
  ggplot(aes(x=pac, y=dmi, color=factor(g))) +
  geom_point(size=1.2, alpha=0.2) +
  scale_color_manual("g", values = c(
    "lightsteelblue3",
    "lightskyblue3",
    "steelblue3",
    "steelblue4",
    "slateblue2", 
    "slateblue3",
    "mediumpurple4"
    )) +
  stat_smooth(method="lm", se = FALSE, alpha=1) +
  geom_hline(yintercept=0, color="dark grey") + 
  labs(y=expression(paste(Delta, "MI")), x="Phase-amplitude coupling") +
  theme_classic2() +
  theme(strip.background = element_blank()) +
  theme(legend.position = "none") +
  theme(legend.background = element_rect(colour ="black")) +
  theme(legend.key.size = unit(.3, "cm")) +
  theme(strip.text.x = element_blank()) +
  theme(strip.text.y = element_text(angle = 0, face = "bold")) +
  facet_grid(model~., scale = "free_y") ->
  p3

p1 / p2 / p3 + plot_layout(guides = "collect") +
  plot_annotation(tag_levels = 'a', tag_suffix = ".")
ggsave("figures/pac.pdf", dpi=600)
```

# Figure - Div/sub intro
```{r, fig.width=3.2, fig.height=1.8, echo=FALSE, warning=FALSE, message=FALSE}
input = -20:40

fi = data.frame(
  ref=phi2(input, 1, 0), 
  II=phi2((input/1.5)-10, 1, 0))

fi %>% 
  gather(model, fi, II) -> fi

fi %>% 
  filter(model != "ref") %>% 
  ggplot(aes(x=input, y=fi)) +
  geom_line() +
  geom_line(aes(x=input, y=ref), color="black", linetype = 2) +
  facet_grid(model~.) +
  labs(x="Input", y="Output", title="Neural arithmetic") +
  theme_classic2() +
  theme(plot.title = element_text(size = 7, hjust=1, face = "bold")) +
  theme(strip.background = element_blank()) +
  theme(legend.background = element_rect(colour ="black")) +
  theme(legend.key.size = unit(.3, "cm")) +
  theme(strip.text.y = element_text(face = "bold", angle = 0)) ->
  p0

# --------------------------------------------------------------
## Panel - Example
examples <- read_csv("../data/examples.csv")
example_dists <- read_csv("../data/example_dists.csv")

examples %>% 
  ggplot(aes(x=times, y=div_sub_p)) +
  geom_line() +
  geom_line(aes(x=times, y=stim_ref), color="darkgrey") +
  scale_y_continuous(breaks=c(0, 0.5, 1), limits=c(0, 1)) +
  labs(x="Time", y="II", title="Example timecourse") +
  theme_classic2() + 
  theme(plot.title = element_text(size = 7, hjust=1, face = "bold")) +
  theme(axis.title.y=element_text(angle = 0, vjust = 0.5, face="bold")) ->
p1

## Dist
example_dists %>% 
  ggplot(aes(x=m, y=div_sub_p)) +
  geom_bar(stat="identity", alpha=1) +
  geom_bar(aes(x=m, y=stim_ref), fill="darkgrey", alpha=0.6, stat="identity") +
  scale_x_continuous(breaks=0:9, labels=1:10) +
  labs(y="Probability", x="m", title="Distribution") +
  lims(y=c(0,1)) +
  theme_classic2() + 
  theme(plot.title = element_text(size = 7, hjust=1, face = "bold")) -> p2

b1 <- p0 + p1 + p2 + plot_layout(widths = c(0.2, 0.6, 0.3))

# --------------------------------------------------------------
## Panel - MI
dmi_exp13 %>%
  filter(num_pop == 50) %>% 
  gather(model, mi, back_p:div_sub_p) %>% 
  filter(model %in% c("div_sub_p")) -> tmp

tmp$model <- revalue(tmp$model, c("div_sub_p"="II")) 

tmp %>% 
  ggplot(aes(x=model, y=mi)) +
  geom_jitter(size=.04, alpha=0.15) +
  stat_summary(aes(group=model), fun.y=median, 
               geom="point", colour="grey", alpha=1, size=10, shape="_") +
  geom_hline(yintercept=0, color="dark grey", size=0.5) + xlab("") +
  lims(y=c(-.35, 0.5)) +
  labs(y=expression(paste(Delta, "MI")), x="", title="") +
  theme_classic() + 
  theme(plot.title = element_text(size = 7, hjust=3, face = "bold")) -> 
  p1

# --------------------------------------------------------------
dmi_exp13 %>% 
  group_by(stim_rate, g, num_pop, q) %>%
  summarise(add_p=mean(add_p),
            back_p=mean(back_p),
            div_sub_p=mean(div_sub_p),
            mult_p=mean(mult_p),
            osc_p=mean(osc_p),
            stim_p=mean(stim_p),
            sub_p=mean(sub_p)) %>%
  ungroup() %>%
  gather(model, mi, add_p:sub_p) -> tmp

tmp %>% 
  filter(model %in% c("div_sub_p")) %>% 
  filter(num_pop == 50) %>% 
  ggplot(aes(x=stim_rate, y=mi, color=factor(g), group=g)) +
  scale_color_manual("g", values = c(
    "lightsteelblue3",
    "lightskyblue3",
    "steelblue3",
    "steelblue4",
    "slateblue2", 
    "slateblue3",
    "mediumpurple4"
    )) +
  geom_line(size=0.5, alpha=0.9) +
  geom_point(size=0.7, alpha=1) +
  geom_hline(yintercept=0, color="dark grey") + xlab("") +
  lims(y=c(-.3, 0.5)) +
  labs(y=expression(paste(Delta, "MI")), 
       x="Stimulus firing rate", 
       title='Divisive fraction') +
  theme_classic() +
  theme(strip.background = element_blank()) +
  theme(plot.title = element_text(size = 7, hjust=0, face = "bold")) +
  theme(legend.background = element_rect(colour ="black")) +
  theme(legend.key.size = unit(.3, "cm")) +
  facet_grid(.~q) -> p2

# --------------------------------------------------------------
## Build Figure
b2 <- p1 + p2 + plot_layout(widths = c(0.07, 0.9))
(b1 / b2) + plot_layout(heights = c(0.4, 0.6)) + 
  plot_annotation(tag_levels = 'a', tag_suffix = ".")
ggsave("figures/ii.pdf", dpi=600)
```

